#!/bin/sh
# Regenerates site/viewer/index.html from the pipeline's demo shell (run after a rebake / build.sh)
# and keeps site/viewer/bundle.js pointing at three-viewer/demo/bundle.js. Run from anywhere.
set -e
cd "$(dirname "$0")/.."
DEMO=../three-viewer/demo
python3 - "$DEMO/aspirium_demo.html" <<'PY'
import pathlib, sys
demo = pathlib.Path(sys.argv[1]).read_bytes()
i = demo.find(b"<script>\n"); shell = demo[:i].decode()
reps = [
  ("<title>ASPIRIUM</title>", "<title>Signet — viewer</title>\n<meta name=\"robots\" content=\"noindex, nofollow\">"),
  ('<meta name="aspirium-dpr" content="1.5">', '<meta name="aspirium-dpr" content="2">'),
  ('<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&display=swap">\n', ''),
  ("body { margin: 0; background: #181818;", "body { margin: 0; background: #000000;"),
]
for a, b in reps:
    assert shell.count(a) == 1, "shell changed upstream: " + a[:50]
    shell = shell.replace(a, b)
head = ("<!doctype html>\n<!-- site/viewer/index.html — embed shell for the pipeline's bundle. GENERATED by site/dev/sync-viewer.sh from\n"
        "     three-viewer/demo/aspirium_demo.html (the panel markup below is required by the bundle and stays hidden).\n"
        "     bundle.js is a symlink to three-viewer/demo/bundle.js so the band always shows the current bake. -->\n")
bridge = r'''<script>
// Page bridge: reports the bundle's state to the embedding page and takes play/pause commands.
// postMessage rather than direct window access, so it also works when the page is opened from
// disk (file:// frames are cross-origin). Counterpart: site/js/viewer-embed.js.
(() => {
  if (window === window.parent) return;                       // opened directly: nothing to report to
  const q = new URLSearchParams(location.search);
  const post = (event, detail) => parent.postMessage({ signet: "viewer", event, detail }, "*");
  let ready = false, ended = false, lit = false, dur = 0;
  addEventListener("error", e => { if (!ready) post("error", String(e.message || "viewer error")); });
  const poll = () => {
    const status = (document.getElementById("status") || {}).textContent || "";
    if (/LOAD ERROR/.test(status)) return post("error", status);
    if (!ready && typeof window.__prewarmMs === "function") {
      ready = true;
      const canvas = document.querySelector("#stage canvas");   // R3 insurance for a bundle built before 2026-09-07
      if (canvas) canvas.style.touchAction = "pan-y";
      dur = parseFloat(document.getElementById("scrub").max) || 0;
      if (q.get("intro") === "skip") {                            // reduced motion / return visit: end pose at once
        __setTime(dur - 0.02); __advance(0.05);                   // lands the intro: unlock + power_on, wordmark at 0.5 s
      }
      post("ready");
    }
    // the page paces the lockup's decode on the ring's own clock, so report where the intro is
    if (ready && !ended && dur) { try { post("introProgress", Math.min(1, JSON.parse(__dbg()).t / dur)); } catch (err) {} }
    if (ready && !ended && window.__unlocked && __unlocked()) { ended = true; post("introEnd"); }
    if (ended && !lit) {
      const on = JSON.parse(__stateDbg()).find(s => s.name === "power_on");
      if (on && on.time >= 0.5) { lit = true; post("wordmarkLit"); }
    }
    if (!(ready && ended && lit)) setTimeout(poll, 150);
  };
  setTimeout(poll, 150);
  addEventListener("message", e => {
    if (e.source !== parent || !e.data || e.data.signet !== "page") return;
    const unlocked = !!(window.__unlocked && __unlocked());     // after the intro, __freeze(false) would replay power_on
    if (e.data.cmd === "pause") { if (!unlocked && window.__freeze) __freeze(true); if (window.__pace) __pace(1); }
    if (e.data.cmd === "play")  { if (!unlocked && window.__freeze) __freeze(false); if (window.__pace) __pace(0); }
  });
})();
</script>
'''
pathlib.Path("viewer/index.html").write_text(head + shell + bridge + '<script src="bundle.js"></script>\n')
print("viewer/index.html regenerated")
PY
# A COPY, not a symlink. The bundle has to be a real file in the repository: git stores a symlink
# as its target path, and the target lives outside this folder, so a clone or a CI checkout would
# get a dangling link and the hero band would 404. Re-run this after every pipeline build.sh.
cp -f "$DEMO/bundle.js" viewer/bundle.js
ls -la viewer
